# Generated by Django 6.0.1 on 2026-01-26 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("filename", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "filetype",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "DOCX"),
                            ("txt", "TXT"),
                            ("pptx", "PPTX"),
                            ("csv", "CSV"),
                            ("images", "Images"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=16,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("top_ids", models.TextField(blank=True, null=True)),
                ("answer", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("chroma_id", models.CharField(blank=True, max_length=256, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="DocumentApp.document",
                    ),
                ),
            ],
            options={
                "ordering": ("chunk_index",),
                "unique_together": {("document", "chunk_index")},
            },
        ),
    ]
